from __future__ import annotations

import argparse
import logging
import webbrowser
from importlib import resources
from pathlib import Path

from workpytools.processing.base import Processor

logger = logging.getLogger(__name__)


def _help_html_path() -> Path:
    """The bundled help.html shipped as package data (workpytools/data/help.html).

    Regenerated by `python scripts/gen_help.py` (also run by the pre-commit
    hook) whenever a command's help text changes, and copied into both
    doc/help.html (dev convenience) and this package-data location so
    `pip install`-ed users get a working `toolh`/`tools help` too.
    """
    return Path(str(resources.files("workpytools.data") / "help.html"))


class HelpProcessor(Processor):
    """Open the bundled help.html (a one-liner summary + full --help for
    every command) in the default browser."""

    name = "help"
    help = "全コマンドのヘルプ一覧(doc/help.html)をブラウザで開く"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "--no-open", action="store_true", help="ブラウザを開かず、パスの表示のみ行う"
        )

    def run(self, args: argparse.Namespace) -> int:
        help_html_path = _help_html_path()
        if not help_html_path.exists():
            raise SystemExit(
                f"help.htmlが見つかりません: {help_html_path}\n"
                "python scripts/gen_help.py を実行して生成してください。"
            )

        logger.info("ヘルプページを開きます: %s", help_html_path)
        print(help_html_path)

        if not args.no_open:
            webbrowser.open(help_html_path.as_uri())

        return 0
