from __future__ import annotations

import argparse
import logging
import webbrowser
from pathlib import Path

from tools.processing.base import Processor

logger = logging.getLogger(__name__)

# リポジトリ直下の doc/help.html。commit時のpre-commitフックで最新化される
# （scripts/gen_help.py 参照）。このコマンド自体は生成せず、既存ファイルを開くだけ。
_HELP_HTML_PATH = Path(__file__).resolve().parents[3] / "doc" / "help.html"


class HelpProcessor(Processor):
    """Open doc/help.html (a one-liner summary + full --help for every command)
    in the default browser.

    doc/help.html is regenerated by a pre-commit hook (scripts/gen_help.py)
    whenever a command's help text changes, so it always reflects the last
    committed state, not necessarily uncommitted local edits.
    """

    name = "help"
    help = "全コマンドのヘルプ一覧(doc/help.html)をブラウザで開く"

    def add_arguments(self, parser: argparse.ArgumentParser) -> None:
        parser.add_argument(
            "--no-open", action="store_true", help="ブラウザを開かず、パスの表示のみ行う"
        )

    def run(self, args: argparse.Namespace) -> int:
        if not _HELP_HTML_PATH.exists():
            raise SystemExit(
                f"help.htmlが見つかりません: {_HELP_HTML_PATH}\n"
                "python scripts/gen_help.py を実行して生成してください。"
            )

        logger.info("ヘルプページを開きます: %s", _HELP_HTML_PATH)
        print(_HELP_HTML_PATH)

        if not args.no_open:
            webbrowser.open(_HELP_HTML_PATH.as_uri())

        return 0
